title = "openBVE Documentation"
theme = "openbve_documentation"
DefaultContentLanguage = "en"
removePathAccents = "true"

relativeURLs = "true"
uglyURLs = "true"

disableKinds = ["page", "404", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[params]
  logoimage = "/images/logo.png"

[blackfriday]
  hrefTargetBlank = true
  extensions = ["laxHtmlBlocks"]

[languages]
[languages.en]
contentDir = "content/en"
baseURL = "/en"
languageName = "English"
weight = 1
[languages.ja]
contentDir = "content/ja"
baseURL = "/ja"
languageName = "日本語"
weight = 2
